version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - APP_DATABASE_HOST=postgres
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USER=postgres
      - APP_DATABASE_PASSWORD=postgres
      - APP_DATABASE_NAME=amazon_inventory
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - fba-inventory-network
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Mount init scripts to create tables
      - ../amazon-app/db/init:/docker-entrypoint-initdb.d
    networks:
      - fba-inventory-network
    restart: unless-stopped

networks:
  fba-inventory-network:
    driver: bridge

volumes:
  postgres-data: 